<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_qsu88IzeEey2BNhv0SqMZA" name="Nivel 2 Salida" author="aaron" bonitaVersion="7.13.0" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_qsu88YzeEey2BNhv0SqMZA" name="Apertura Cuenta Bancaria">
      <elements xmi:type="process:Lane" xmi:id="_qsu88ozeEey2BNhv0SqMZA" name="Nivel 2 - Subproceso SALIDA" actor="_qsu9C4zeEey2BNhv0SqMZA">
        <elements xmi:type="process:StartEvent" xmi:id="_qsu884zeEey2BNhv0SqMZA" name="Inicio" outgoing="_e--qcIzgEey2BNhv0SqMZA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qsu89IzeEey2BNhv0SqMZA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qsu89YzeEey2BNhv0SqMZA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qsu89ozeEey2BNhv0SqMZA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="__HYcMIzeEey2BNhv0SqMZA" name="Empleado: Enviar correo electrónico con los datos de gestión de la cuenta" outgoing="_0g_P0IzfEey2BNhv0SqMZA" incoming="__renwIzeEey2BNhv0SqMZA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__HZDQYzeEey2BNhv0SqMZA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__HZDQIzeEey2BNhv0SqMZA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__HZDQozeEey2BNhv0SqMZA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="__HZDQ4zeEey2BNhv0SqMZA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="__HZDRIzeEey2BNhv0SqMZA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="__HZDRYzeEey2BNhv0SqMZA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="__HZDR4zeEey2BNhv0SqMZA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="__HZDRozeEey2BNhv0SqMZA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_zYFHAIzfEey2BNhv0SqMZA" name="Cliente: Seguir los pasos para comenzar a utilizar la cuenta bancaria" outgoing="_A_bGcIzgEey2BNhv0SqMZA" incoming="_0g_P0IzfEey2BNhv0SqMZA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zYFuEIzfEey2BNhv0SqMZA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zYFHAYzfEey2BNhv0SqMZA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zYFuEYzfEey2BNhv0SqMZA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_zYFuEozfEey2BNhv0SqMZA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_zYFuE4zfEey2BNhv0SqMZA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_zYFuFIzfEey2BNhv0SqMZA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_zYFuFozfEey2BNhv0SqMZA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_zYFuFYzfEey2BNhv0SqMZA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_ANIt4IzgEey2BNhv0SqMZA" name="Fin" incoming="_A_bGcIzgEey2BNhv0SqMZA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ANJU8YzgEey2BNhv0SqMZA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ANJU8IzgEey2BNhv0SqMZA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ANJU8ozgEey2BNhv0SqMZA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_R9H9sIzgEey2BNhv0SqMZA" name="Empleado: Crear cuenta con los datos del cliente  " outgoing="__renwIzeEey2BNhv0SqMZA" incoming="_e--qcIzgEey2BNhv0SqMZA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_R9H9sozgEey2BNhv0SqMZA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_R9H9sYzgEey2BNhv0SqMZA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_R9H9s4zgEey2BNhv0SqMZA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_R9H9tIzgEey2BNhv0SqMZA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_R9H9tYzgEey2BNhv0SqMZA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_R9H9tozgEey2BNhv0SqMZA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_R9IkwYzgEey2BNhv0SqMZA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_R9IkwIzgEey2BNhv0SqMZA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_qsu9BIzeEey2BNhv0SqMZA">
        <targetForm xmi:type="expression:Expression" xmi:id="_qsu9BYzeEey2BNhv0SqMZA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_qsu9BozeEey2BNhv0SqMZA">
        <targetForm xmi:type="expression:Expression" xmi:id="_qsu9B4zeEey2BNhv0SqMZA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="__renwIzeEey2BNhv0SqMZA" target="__HYcMIzeEey2BNhv0SqMZA" source="_R9H9sIzgEey2BNhv0SqMZA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__rfO0IzeEey2BNhv0SqMZA"/>
        <condition xmi:type="expression:Expression" xmi:id="__rfO0YzeEey2BNhv0SqMZA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0g_P0IzfEey2BNhv0SqMZA" target="_zYFHAIzfEey2BNhv0SqMZA" source="__HYcMIzeEey2BNhv0SqMZA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0g_P0YzfEey2BNhv0SqMZA"/>
        <condition xmi:type="expression:Expression" xmi:id="_0g_P0ozfEey2BNhv0SqMZA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_A_bGcIzgEey2BNhv0SqMZA" target="_ANIt4IzgEey2BNhv0SqMZA" source="_zYFHAIzfEey2BNhv0SqMZA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_A_btgIzgEey2BNhv0SqMZA"/>
        <condition xmi:type="expression:Expression" xmi:id="_A_btgYzgEey2BNhv0SqMZA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_e--qcIzgEey2BNhv0SqMZA" target="_R9H9sIzgEey2BNhv0SqMZA" source="_qsu884zeEey2BNhv0SqMZA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_e-_RgIzgEey2BNhv0SqMZA"/>
        <condition xmi:type="expression:Expression" xmi:id="_e-_RgYzgEey2BNhv0SqMZA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_qsu9C4zeEey2BNhv0SqMZA" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_qsu9DIzeEey2BNhv0SqMZA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qsu9DYzeEey2BNhv0SqMZA">
        <name xmi:type="expression:Expression" xmi:id="_qsu9DozeEey2BNhv0SqMZA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qsu9D4zeEey2BNhv0SqMZA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qsu9EIzeEey2BNhv0SqMZA">
        <name xmi:type="expression:Expression" xmi:id="_qsu9EYzeEey2BNhv0SqMZA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qsu9EozeEey2BNhv0SqMZA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qsu9E4zeEey2BNhv0SqMZA">
        <name xmi:type="expression:Expression" xmi:id="_qsu9FIzeEey2BNhv0SqMZA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qsu9FYzeEey2BNhv0SqMZA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qsu9FozeEey2BNhv0SqMZA">
        <name xmi:type="expression:Expression" xmi:id="_qsu9F4zeEey2BNhv0SqMZA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qsu9GIzeEey2BNhv0SqMZA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qsu9GYzeEey2BNhv0SqMZA">
        <name xmi:type="expression:Expression" xmi:id="_qsu9GozeEey2BNhv0SqMZA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qsu9G4zeEey2BNhv0SqMZA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_qsu9HIzeEey2BNhv0SqMZA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_qsu9HYzeEey2BNhv0SqMZA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_qsu9HozeEey2BNhv0SqMZA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_qsu9H4zeEey2BNhv0SqMZA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_qsu9IIzeEey2BNhv0SqMZA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_qsu9IYzeEey2BNhv0SqMZA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_qsu9IozeEey2BNhv0SqMZA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_qsu9I4zeEey2BNhv0SqMZA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_qsu9JIzeEey2BNhv0SqMZA" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_qsu9JYzeEey2BNhv0SqMZA" type="Process" element="_qsu88IzeEey2BNhv0SqMZA" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_qsu9JozeEey2BNhv0SqMZA" type="2007" element="_qsu88YzeEey2BNhv0SqMZA">
      <children xmi:type="notation:DecorationNode" xmi:id="_qsu9J4zeEey2BNhv0SqMZA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_qsu9KIzeEey2BNhv0SqMZA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_qsu9KYzeEey2BNhv0SqMZA" type="3007" element="_qsu88ozeEey2BNhv0SqMZA">
          <children xmi:type="notation:DecorationNode" xmi:id="_qsu9KozeEey2BNhv0SqMZA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_qsu9K4zeEey2BNhv0SqMZA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_qsu9L4zeEey2BNhv0SqMZA" type="3002" element="_qsu884zeEey2BNhv0SqMZA" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_qsu9MIzeEey2BNhv0SqMZA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_qsu9MYzeEey2BNhv0SqMZA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qsu9MozeEey2BNhv0SqMZA" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__HaRYIzeEey2BNhv0SqMZA" type="3006" element="__HYcMIzeEey2BNhv0SqMZA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__HbfgIzeEey2BNhv0SqMZA" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__Ha4cIzeEey2BNhv0SqMZA" x="327" y="43" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zYG8MIzfEey2BNhv0SqMZA" type="3006" element="_zYFHAIzfEey2BNhv0SqMZA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_zYG8MozfEey2BNhv0SqMZA" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zYG8MYzfEey2BNhv0SqMZA" x="536" y="48" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ANKjEIzgEey2BNhv0SqMZA" type="3003" element="_ANIt4IzgEey2BNhv0SqMZA" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_ANLKIIzgEey2BNhv0SqMZA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ANLKIYzgEey2BNhv0SqMZA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ANKjEYzgEey2BNhv0SqMZA" x="707" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_R9Jy4IzgEey2BNhv0SqMZA" type="3006" element="_R9H9sIzgEey2BNhv0SqMZA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_R9Jy4ozgEey2BNhv0SqMZA" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_R9Jy4YzgEey2BNhv0SqMZA" x="137" y="48" width="140" height="70"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_qsu9M4zeEey2BNhv0SqMZA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_qsu9NIzeEey2BNhv0SqMZA" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_qsu9NYzeEey2BNhv0SqMZA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_qsu9NozeEey2BNhv0SqMZA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qsu9N4zeEey2BNhv0SqMZA"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_qsu9OIzeEey2BNhv0SqMZA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_qsu9OYzeEey2BNhv0SqMZA" fontName="Ubuntu"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_qsu9OozeEey2BNhv0SqMZA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_qsu9O4zeEey2BNhv0SqMZA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qsu9PIzeEey2BNhv0SqMZA" width="870" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_qsu9PYzeEey2BNhv0SqMZA"/>
    <edges xmi:type="notation:Connector" xmi:id="__rf14IzeEey2BNhv0SqMZA" type="4001" element="__renwIzeEey2BNhv0SqMZA" source="_R9Jy4IzgEey2BNhv0SqMZA" target="__HaRYIzeEey2BNhv0SqMZA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__rgc8IzeEey2BNhv0SqMZA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__rgc8YzeEey2BNhv0SqMZA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__rf14YzeEey2BNhv0SqMZA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__rf14ozeEey2BNhv0SqMZA" points="[0, -13, -92, 0]$[85, -13, -7, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__rkuYIzeEey2BNhv0SqMZA" id="(0.93,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="__rkuYYzeEey2BNhv0SqMZA" id="(0.07,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0hAd8IzfEey2BNhv0SqMZA" type="4001" element="_0g_P0IzfEey2BNhv0SqMZA" source="__HaRYIzeEey2BNhv0SqMZA" target="_zYG8MIzfEey2BNhv0SqMZA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0hBFAIzfEey2BNhv0SqMZA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0hBFAYzfEey2BNhv0SqMZA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0hAd8YzfEey2BNhv0SqMZA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0hAd8ozfEey2BNhv0SqMZA" points="[0, 7, -69, -4]$[49, 7, -20, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0hEIUIzfEey2BNhv0SqMZA" id="(1.0,0.425)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0hEIUYzfEey2BNhv0SqMZA" id="(0.13,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_A_cUkIzgEey2BNhv0SqMZA" type="4001" element="_A_bGcIzgEey2BNhv0SqMZA" source="_zYG8MIzfEey2BNhv0SqMZA" target="_ANKjEIzgEey2BNhv0SqMZA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_A_c7oIzgEey2BNhv0SqMZA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_A_c7oYzgEey2BNhv0SqMZA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_A_cUkYzgEey2BNhv0SqMZA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_A_cUkozgEey2BNhv0SqMZA" points="[0, 1, -88, 0]$[86, 0, -2, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_A_gmAIzgEey2BNhv0SqMZA" id="(1.0,0.45714285714285713)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_A_gmAYzgEey2BNhv0SqMZA" id="(0.06666666666666667,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_e-_4kIzgEey2BNhv0SqMZA" type="4001" element="_e--qcIzgEey2BNhv0SqMZA" source="_qsu9L4zeEey2BNhv0SqMZA" target="_R9Jy4IzgEey2BNhv0SqMZA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_e-_4k4zgEey2BNhv0SqMZA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_e-_4lIzgEey2BNhv0SqMZA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_e-_4kYzgEey2BNhv0SqMZA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_e-_4kozgEey2BNhv0SqMZA" points="[-1, -9, -58, 0]$[47, -9, -10, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_e_BGsIzgEey2BNhv0SqMZA" id="(1.0,0.8666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_e_BGsYzgEey2BNhv0SqMZA" id="(0.07142857142857142,0.5285714285714286)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
